services:
    oxpus.dlext.controller:
        class: oxpus\dlext\controller\main
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
            - '@service_container'
            - '@ext.manager'
            - '@path_helper'
            - '@dbal.conn'
            - '@config'
            - '@log'
            - '@controller.helper'
            - '@auth'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
    oxpus.dlext.listener:
        class: oxpus\dlext\event\main_listener
        arguments:
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%core.table_prefix%'
            - '@ext.manager'
            - '@path_helper'
            - '@service_container'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@auth'
            - '@template'
            - '@user'
            - '@language'
        tags:
            - { name: event.listener }
    oxpus.dlext.notification.type.dlext:
        class: oxpus\dlext\notification\dlext
        shared: false
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.user_notifications%'
            - '@controller.helper'
            - '@language'
        tags:
            - { name: notification.type }
